### ISSUE TITLE
Merge PR fixing conceptual error

### ISSUE THREAD

**Issue by coto** [google/dspl#41]
I left PR #40 fixing a conceptual error of currencies that you had about my country. Please someone close it or merge it since I won't sign the CLA agreement to pass the check.
BR

**Comment by nkrishnaswami** [comment]
Hello @coto,
The change is good, but unfortunately there is no provision for exceptions to the policy to merge PRs only from authors with a CLA on file.
As an alternative, let's make an issue describing the problem, and have one of the other maintainers/contributors fix it there.

**Comment by nkrishnaswami** [comment]
Looks like there are 22 other rows with this problem.  The new issue will cover those, as well.  Thanks, @coto!
